# Generated by Django 6.0.3 on 2026-05-16 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessModule',
            fields=[
                ('slug', models.CharField(default='erp', max_length=64, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'ERP access module',
                'verbose_name_plural': 'ERP access modules',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AccessGroupMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(choices=[('role', 'Role-based'), ('department', 'Department-based')], max_length=20)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_meta', to='auth.group')),
            ],
            options={
                'verbose_name': 'Access group metadata',
                'verbose_name_plural': 'Access group metadata',
            },
        ),
    ]
