# Generated by Django 6.0.3 on 2026-04-20 07:13

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MstCoatType',
            fields=[
                ('coating_id', models.AutoField(primary_key=True, serialize=False)),
                ('coating_name', models.CharField(max_length=150, unique=True, verbose_name='Coating Type')),
            ],
            options={
                'verbose_name': 'Coating Type',
                'verbose_name_plural': 'Coating Types',
                'db_table': 'MstCoatType',
                'ordering': ['coating_name'],
            },
        ),
        migrations.CreateModel(
            name='MstColor',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=150, unique=True, verbose_name='Colour Name')),
            ],
            options={
                'verbose_name': 'Colour',
                'verbose_name_plural': 'Colours',
                'db_table': 'MstColor',
                'ordering': ['color_name'],
            },
        ),
        migrations.CreateModel(
            name='MstCust',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=200, unique=True, verbose_name='Customer Name')),
                ('short_name', models.CharField(max_length=10, unique=True, verbose_name='Short Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('pin_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Pin Code')),
                ('landline_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Land Line No.')),
                ('mobile_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='Mobile No.')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email ID')),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN No.')),
                ('gst_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='GST No.')),
                ('udyam_cert', models.CharField(blank=True, max_length=30, null=True, verbose_name='Udyam Certificate')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'MstCust',
                'ordering': ['cust_name'],
            },
        ),
        migrations.CreateModel(
            name='MstDepartment',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=150, unique=True, verbose_name='Department Name')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'MstDepartment',
                'ordering': ['dept_name'],
            },
        ),
        migrations.CreateModel(
            name='MstExpenses',
            fields=[
                ('exp_id', models.AutoField(primary_key=True, serialize=False)),
                ('exp_name', models.CharField(max_length=200, unique=True, verbose_name='Expense Name')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'MstExpenses',
                'ordering': ['exp_name'],
            },
        ),
        migrations.CreateModel(
            name='MstItemType',
            fields=[
                ('item_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_type_name', models.CharField(max_length=150, unique=True, verbose_name='Item Type Name')),
            ],
            options={
                'verbose_name': 'Item Type',
                'verbose_name_plural': 'Item Types',
                'db_table': 'MstItemType',
                'ordering': ['item_type_name'],
            },
        ),
        migrations.CreateModel(
            name='MstPdnStage',
            fields=[
                ('stage_id', models.AutoField(primary_key=True, serialize=False)),
                ('stage_name', models.CharField(max_length=150, unique=True, verbose_name='Production Stage')),
            ],
            options={
                'verbose_name': 'Production Stage',
                'verbose_name_plural': 'Production Stages',
                'db_table': 'MstPdnStage',
                'ordering': ['stage_name'],
            },
        ),
        migrations.CreateModel(
            name='MstProdCat',
            fields=[
                ('prod_cat_id', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Category ID')),
                ('prod_cat_name', models.CharField(max_length=150, unique=True, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'db_table': 'MstProdCat',
                'ordering': ['prod_cat_name'],
            },
        ),
        migrations.CreateModel(
            name='MstShape',
            fields=[
                ('shape_id', models.AutoField(primary_key=True, serialize=False)),
                ('shape_name', models.CharField(max_length=150, unique=True, verbose_name='Shape Name')),
            ],
            options={
                'verbose_name': 'Product Shape',
                'verbose_name_plural': 'Product Shapes',
                'db_table': 'MstShape',
                'ordering': ['shape_name'],
            },
        ),
        migrations.CreateModel(
            name='MstState',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=150, unique=True, verbose_name='State Name')),
                ('gst_code', models.CharField(max_length=10, unique=True, verbose_name='GST Code')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'MstState',
                'ordering': ['state_name'],
            },
        ),
        migrations.CreateModel(
            name='MstTransport',
            fields=[
                ('transport_id', models.AutoField(primary_key=True, serialize=False)),
                ('transport_name', models.CharField(max_length=200, unique=True, verbose_name='Transporter Name')),
            ],
            options={
                'verbose_name': 'Transporter',
                'verbose_name_plural': 'Transporters',
                'db_table': 'MstTransport',
                'ordering': ['transport_name'],
            },
        ),
        migrations.CreateModel(
            name='MstUom',
            fields=[
                ('uom_id', models.AutoField(primary_key=True, serialize=False)),
                ('uom_name', models.CharField(max_length=150, unique=True, verbose_name='UOM Name')),
                ('short_name', models.CharField(max_length=3, unique=True, verbose_name='Abbreviation')),
            ],
            options={
                'verbose_name': 'Unit of Measurement',
                'verbose_name_plural': 'Units of Measurement',
                'db_table': 'MstUom',
                'ordering': ['uom_name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('fy_id', models.AutoField(primary_key=True, serialize=False)),
                ('fy_start_year', models.PositiveIntegerField(db_index=True, help_text='e.g. 2025 for FY 2025-26', unique=True, verbose_name='FY Start Year')),
                ('fy_end_year', models.PositiveIntegerField(help_text='e.g. 2026 for FY 2025-26', verbose_name='FY End Year')),
                ('fy_display', models.CharField(help_text='Format: "2025-26"', max_length=9, verbose_name='FY Display')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_current', models.BooleanField(default=False, verbose_name='Current')),
                ('is_open', models.BooleanField(default=True, verbose_name='Open')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Closed')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Financial Year',
                'verbose_name_plural': 'Financial Years',
                'db_table': 'MstFinYr',
                'ordering': ['-fy_start_year'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fy_end_year', django.db.models.expressions.CombinedExpression(models.F('fy_start_year'), '+', models.Value(1)))), name='mst_finyr_end_year_is_start_plus_1'), models.CheckConstraint(condition=models.Q(('start_date__day', 1), ('start_date__month', 4)), name='mst_finyr_start_date_is_apr_1'), models.CheckConstraint(condition=models.Q(('end_date__day', 31), ('end_date__month', 3)), name='mst_finyr_end_date_is_mar_31'), models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='mst_finyr_start_date_lte_end_date'), models.CheckConstraint(condition=models.Q(('is_current', True), ('is_closed', True), _negated=True), name='mst_finyr_current_not_closed')],
            },
        ),
        migrations.CreateModel(
            name='MstCapsule',
            fields=[
                ('capsule_id', models.AutoField(primary_key=True, serialize=False)),
                ('capsule_name', models.CharField(max_length=200, unique=True, verbose_name='Capsule Name')),
                ('capsule_size', models.CharField(max_length=100, verbose_name='Capsule Size')),
                ('capsule_color', models.CharField(max_length=100, verbose_name='Capsule Colour')),
            ],
            options={
                'verbose_name': 'Capsule Type',
                'verbose_name_plural': 'Capsule Types',
                'db_table': 'MstCapsule',
                'ordering': ['capsule_name'],
                'constraints': [models.UniqueConstraint(fields=('capsule_size', 'capsule_color'), name='unique_capsule_size_color')],
            },
        ),
        migrations.CreateModel(
            name='MstItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200, unique=True, verbose_name='Item Name')),
                ('hsn_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='HSN Code')),
                ('min_level', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Minimum Stock Level')),
                ('max_level', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Maximum Stock Level')),
                ('maintain_batch', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='Maintain Batches')),
                ('mfg_date', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='Manufacturing Date')),
                ('exp_date', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='Expiry Date')),
                ('last_purchase_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Last Purchase Rate')),
                ('item_type', models.ForeignKey(db_column='item_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='masters.mstitemtype', verbose_name='Item Type')),
                ('item_category', models.ForeignKey(db_column='item_cat_id', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='masters.mstprodcat', verbose_name='Item Category')),
                ('uom', models.ForeignKey(blank=True, db_column='uom_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='masters.mstuom', verbose_name='UOM')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'MstItem',
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='MstPkgStyle',
            fields=[
                ('pkg_style_id', models.AutoField(primary_key=True, serialize=False)),
                ('pkg_style_name', models.CharField(max_length=150, verbose_name='Packing Style Name')),
                ('pkg_style_value', models.PositiveIntegerField(verbose_name='Packing Style Value')),
                ('pkg_type', models.ForeignKey(db_column='pkg_type_id', on_delete=django.db.models.deletion.PROTECT, to='masters.mstitemtype', verbose_name='Packing Type (Item Type)')),
            ],
            options={
                'verbose_name': 'Packing Style',
                'verbose_name_plural': 'Packing Styles',
                'db_table': 'MstPkgStyle',
                'ordering': ['pkg_style_name'],
            },
        ),
        migrations.CreateModel(
            name='MstProd',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=200, unique=True, verbose_name='Product Name')),
                ('generic_name', models.TextField(verbose_name='Generic Name')),
                ('hsn_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='HSN Code')),
                ('tablet_layer', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double')], default='Single', max_length=10, verbose_name='Tablet Layer Type')),
                ('image_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Product Image Path')),
                ('first_color', models.ForeignKey(blank=True, db_column='first_color_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first_color_products', to='masters.mstcolor', verbose_name='First Layer Colour')),
                ('prod_type', models.ForeignKey(db_column='item_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='masters.mstitemtype', verbose_name='Product Type')),
                ('second_color', models.ForeignKey(blank=True, db_column='second_color_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_color_products', to='masters.mstcolor', verbose_name='Second Layer Colour')),
                ('prod_category', models.ForeignKey(db_column='prod_cat_id', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='masters.mstprodcat', verbose_name='Product Category')),
                ('uom', models.ForeignKey(db_column='uom_id', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='masters.mstuom', verbose_name='Unit of Measurement')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'MstProd',
                'ordering': ['prod_name'],
            },
        ),
        migrations.CreateModel(
            name='MstCustProd',
            fields=[
                ('cust_prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('adv_license', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='Advance License')),
                ('license_details', models.CharField(blank=True, max_length=300, null=True, verbose_name='License Details')),
                ('batch_abbr', models.CharField(max_length=3, verbose_name='Batch Abbreviation')),
                ('customer', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.CASCADE, related_name='cust_products', to='masters.mstcust', verbose_name='Customer')),
                ('product', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.PROTECT, related_name='cust_products', to='masters.mstprod', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Customer Product',
                'verbose_name_plural': 'Customer Products',
                'db_table': 'MstCustProd',
                'ordering': ['customer', 'product'],
            },
        ),
        migrations.CreateModel(
            name='MstBomPmHed',
            fields=[
                ('spec_id', models.AutoField(primary_key=True, serialize=False)),
                ('spec_name', models.CharField(max_length=300, unique=True, verbose_name='Specification Name')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Locked')),
                ('customer', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.PROTECT, related_name='bom_pm_headers', to='masters.mstcust', verbose_name='Customer')),
                ('pkg_style', models.ForeignKey(db_column='pkg_style_id', on_delete=django.db.models.deletion.PROTECT, related_name='bom_pm_headers', to='masters.mstpkgstyle', verbose_name='Packing Style')),
                ('product', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.PROTECT, related_name='bom_pm_headers', to='masters.mstprod', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'BOM PM Header',
                'verbose_name_plural': 'BOM PM Headers',
                'db_table': 'MstBomPmHed',
                'ordering': ['-spec_id'],
            },
        ),
        migrations.AddField(
            model_name='mstitemtype',
            name='item_category',
            field=models.ForeignKey(db_column='prod_cat_id', on_delete=django.db.models.deletion.PROTECT, to='masters.mstprodcat', verbose_name='Item Category'),
        ),
        migrations.CreateModel(
            name='MstSection',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=150, unique=True, verbose_name='Section Name')),
                ('department', models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.PROTECT, to='masters.mstdepartment', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'db_table': 'MstSection',
                'ordering': ['department', 'section_name'],
            },
        ),
        migrations.CreateModel(
            name='MstMachine',
            fields=[
                ('machine_id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_name', models.CharField(max_length=200, unique=True, verbose_name='Machine Name')),
                ('make', models.CharField(blank=True, max_length=150, null=True, verbose_name='Make')),
                ('model_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model No.')),
                ('machine_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Machine No.')),
                ('capacity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Capacity')),
                ('installed_date', models.DateField(blank=True, null=True, verbose_name='Installation Date')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('section', models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.PROTECT, to='masters.mstsection', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'db_table': 'MstMachine',
                'ordering': ['machine_name'],
            },
        ),
        migrations.CreateModel(
            name='MstBomRmHed',
            fields=[
                ('spec_id', models.AutoField(primary_key=True, serialize=False)),
                ('spec_name', models.CharField(max_length=300, unique=True, verbose_name='Specification Name')),
                ('avg_wt', models.PositiveIntegerField(blank=True, null=True, verbose_name='Average Weight')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Locked')),
                ('capsule', models.ForeignKey(blank=True, db_column='capsule_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_rm_headers', to='masters.mstcapsule', verbose_name='Capsule')),
                ('coating', models.ForeignKey(blank=True, db_column='coating_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_rm_headers', to='masters.mstcoattype', verbose_name='Coating')),
                ('color', models.ForeignKey(blank=True, db_column='color_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_rm_headers', to='masters.mstcolor', verbose_name='Colour')),
                ('customer', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.PROTECT, related_name='bom_rm_headers', to='masters.mstcust', verbose_name='Customer')),
                ('product', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.PROTECT, related_name='bom_rm_headers', to='masters.mstprod', verbose_name='Product')),
                ('shape', models.ForeignKey(blank=True, db_column='shape_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_rm_headers', to='masters.mstshape', verbose_name='Shape')),
            ],
            options={
                'verbose_name': 'BOM RM Header',
                'verbose_name_plural': 'BOM RM Headers',
                'db_table': 'MstBomRmHed',
                'ordering': ['-spec_id'],
            },
        ),
        migrations.AddField(
            model_name='mstcust',
            name='state',
            field=models.ForeignKey(db_column='state_id', on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='masters.mststate', verbose_name='State'),
        ),
        migrations.CreateModel(
            name='MstSupplier',
            fields=[
                ('supl_id', models.AutoField(primary_key=True, serialize=False)),
                ('supl_name', models.CharField(max_length=200, unique=True, verbose_name='Supplier Name')),
                ('short_name', models.CharField(max_length=10, unique=True, verbose_name='Short Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('pin_code', models.CharField(max_length=6, verbose_name='Pin Code')),
                ('landline_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='Land Line No.')),
                ('mobile_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='Mobile No.')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email ID')),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN No.')),
                ('gst_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='GST No.')),
                ('udyam_cert', models.CharField(blank=True, max_length=30, null=True, verbose_name='Udyam Certificate')),
                ('state', models.ForeignKey(db_column='state_id', on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='masters.mststate', verbose_name='State')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'mstSupplier',
                'ordering': ['supl_name'],
            },
        ),
        migrations.CreateModel(
            name='MstBomRmDtl',
            fields=[
                ('dtl_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantity')),
                ('spec', models.ForeignKey(db_column='spec_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='masters.mstbomrmhed', verbose_name='Specification')),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.PROTECT, related_name='bom_rm_items', to='masters.mstitem', verbose_name='Item')),
                ('stage', models.ForeignKey(db_column='stage_id', on_delete=django.db.models.deletion.PROTECT, related_name='bom_rm_items', to='masters.mstpdnstage', verbose_name='Stage')),
                ('uom', models.ForeignKey(db_column='uom_id', on_delete=django.db.models.deletion.PROTECT, related_name='bom_rm_items', to='masters.mstuom', verbose_name='UOM')),
            ],
            options={
                'verbose_name': 'BOM RM Item',
                'verbose_name_plural': 'BOM RM Items',
                'db_table': 'MstBomRmDtl',
                'ordering': ['spec_id', 'dtl_id'],
            },
        ),
        migrations.CreateModel(
            name='MstBomPmDtl',
            fields=[
                ('dtl_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantity')),
                ('spec', models.ForeignKey(db_column='spec_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='masters.mstbompmhed', verbose_name='Specification')),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.PROTECT, related_name='bom_pm_items', to='masters.mstitem', verbose_name='Item')),
                ('stage', models.ForeignKey(db_column='stage_id', on_delete=django.db.models.deletion.PROTECT, related_name='bom_pm_items', to='masters.mstpdnstage', verbose_name='Stage')),
                ('uom', models.ForeignKey(db_column='uom_id', on_delete=django.db.models.deletion.PROTECT, related_name='bom_pm_items', to='masters.mstuom', verbose_name='UOM')),
            ],
            options={
                'verbose_name': 'BOM PM Item',
                'verbose_name_plural': 'BOM PM Items',
                'db_table': 'MstBomPmDtl',
                'ordering': ['spec_id', 'dtl_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='mstpkgstyle',
            constraint=models.UniqueConstraint(fields=('pkg_style_name', 'pkg_type'), name='unique_pkgstyle_per_itemtype'),
        ),
        migrations.AddConstraint(
            model_name='mstcustprod',
            constraint=models.UniqueConstraint(fields=('customer', 'product'), name='unique_product_per_customer'),
        ),
        migrations.AddConstraint(
            model_name='mstbompmhed',
            constraint=models.UniqueConstraint(fields=('customer', 'product', 'pkg_style'), name='unique_bom_pm_customer_product_pkgstyle'),
        ),
        migrations.AddConstraint(
            model_name='mstsection',
            constraint=models.UniqueConstraint(fields=('section_name', 'department'), name='unique_section_per_department'),
        ),
        migrations.AddConstraint(
            model_name='mstbomrmdtl',
            constraint=models.UniqueConstraint(fields=('spec', 'stage', 'item'), name='unique_bom_rm_stage_item_per_spec'),
        ),
        migrations.AddConstraint(
            model_name='mstbompmdtl',
            constraint=models.UniqueConstraint(fields=('spec', 'stage', 'item'), name='unique_bom_pm_stage_item_per_spec'),
        ),
    ]
