# Generated by Django — BOM batch size (lakh) and derived batch nos.

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_mstsupplier_short_name_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstbomrmhed',
            name='batch_size',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('1.00'),
                help_text='Quantity in lakh (2 decimal places).',
                max_digits=10,
                verbose_name='Batch size (lakh)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mstbomrmhed',
            name='batch_nos',
            field=models.PositiveBigIntegerField(
                default=100_000,
                help_text='Derived: batch size × 100,000.',
                verbose_name='Batch nos.',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mstbompmhed',
            name='batch_size',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('1.00'),
                help_text='Quantity in lakh (2 decimal places).',
                max_digits=10,
                verbose_name='Batch size (lakh)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mstbompmhed',
            name='batch_nos',
            field=models.PositiveBigIntegerField(
                default=100_000,
                help_text='Derived: batch size × 100,000.',
                verbose_name='Batch nos.',
            ),
            preserve_default=False,
        ),
    ]
