# Generated by Django 6.0.3 on 2026-05-11 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_bom_specname_product_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstOperator',
            fields=[
                ('opt_id', models.AutoField(db_column='Opt_id', primary_key=True, serialize=False)),
                ('opt_name', models.CharField(db_column='Opt_name', max_length=30, unique=True, verbose_name='Operator name')),
                ('designation', models.CharField(blank=True, db_column='Designation', max_length=200, null=True, verbose_name='Designation')),
            ],
            options={
                'verbose_name': 'Operator',
                'verbose_name_plural': 'Operators',
                'db_table': 'mstoperator',
                'ordering': ['opt_name'],
            },
        ),
        migrations.CreateModel(
            name='MstOperatorSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.ForeignKey(db_column='Opt_id', on_delete=django.db.models.deletion.CASCADE, related_name='section_links', to='masters.mstoperator', verbose_name='Operator')),
                ('section', models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.PROTECT, related_name='operator_section_links', to='masters.mstsection', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Operator section',
                'verbose_name_plural': 'Operator sections',
                'db_table': 'MstOperatorSection',
                'constraints': [models.UniqueConstraint(fields=('operator', 'section'), name='uniq_mst_operator_section')],
            },
        ),
    ]
