# Generated by Django 6.0.3 on 2026-05-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_operator_master_and_dpr_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstitem',
            name='sample_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Sample qty'),
        ),
    ]
