# Generated by Django 6.0.3 on 2026-05-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_bom_rm_dtl_section_machine_lots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mstbomrmdtl',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='mstbomrmdtl',
            name='no_of_lots',
        ),
        migrations.RemoveField(
            model_name='mstbomrmdtl',
            name='section',
        ),
    ]
