# Generated by Django 6.0.3 on 2026-05-24 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_remove_mstbomrmdtl_machine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstbomrmhed',
            name='machine',
            field=models.ForeignKey(db_column='machine_id', default=2, on_delete=django.db.models.deletion.PROTECT, related_name='bom_rm_headers', to='masters.mstmachine', verbose_name='Machine'),
            preserve_default=False,
        ),
    ]
