# Generated by Django 6.0.3 on 2026-05-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_mstbomrmhed_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstbomrmhed',
            name='no_of_lots',
            field=models.DecimalField(decimal_places=0, default=2, max_digits=10, verbose_name='No of Lots'),
            preserve_default=False,
        ),
    ]
