# Generated by Django 6.0.3 on 2026-05-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_mstbomrmhed_no_of_lots'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstExpGroup',
            fields=[
                ('exp_group', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Production Stage')),
            ],
            options={
                'verbose_name': 'Expenses Group',
                'verbose_name_plural': 'Expenses Group',
                'db_table': 'MstExpGroup',
                'ordering': ['exp_group'],
            },
        ),
        migrations.AddField(
            model_name='mstexpenses',
            name='exp_group',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Expenses Group'),
        ),
    ]
