# Generated by Django 6.0.3 on 2026-05-27 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_mstexpgroup_mstexpenses_exp_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstexpenses',
            name='exp_group',
            field=models.ForeignKey(db_column='exp_group', default=4, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_group', to='masters.mstexpgroup', verbose_name=''),
            preserve_default=False,
        ),
    ]
