# Generated by Django 6.0.3 on 2026-05-12 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_enabled', models.BooleanField(default=False)),
                ('interval_hours', models.PositiveSmallIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)])),
                ('last_successful_backup_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Database backup settings',
            },
        ),
    ]
