# Generated by Django 6.0.3 on 2026-05-12 14:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0005_operator_master_and_dpr_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvCustMonthlyStock',
            fields=[
                ('inv_mth_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Month')),
                ('opening_qty_lac', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Opening qty (lac)')),
                ('receipt_qty_lac', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Stock moved to the customer during this month.', max_digits=12, verbose_name='Received / supplied (lac)')),
                ('issue_qty_lac', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Stock removed from the customer balance during this month.', max_digits=12, verbose_name='Issued / consumed (lac)')),
                ('remarks', models.CharField(blank=True, max_length=300, verbose_name='Remarks')),
                ('cust_product', models.ForeignKey(db_column='cust_prod_id', on_delete=django.db.models.deletion.CASCADE, related_name='monthly_inventory_rows', to='masters.mstcustprod', verbose_name='Customer product')),
            ],
            options={
                'verbose_name': 'Customer monthly inventory',
                'verbose_name_plural': 'Customer monthly inventory',
                'db_table': 'InvCustMonthlyStock',
                'ordering': ['year', 'month', 'cust_product__customer', 'cust_product__product'],
                'constraints': [models.UniqueConstraint(fields=('cust_product', 'year', 'month'), name='unique_inv_cust_prod_month'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='inv_cust_mth_month_range'), models.CheckConstraint(condition=models.Q(('opening_qty_lac__gte', 0)), name='inv_cust_mth_opening_gte_0'), models.CheckConstraint(condition=models.Q(('receipt_qty_lac__gte', 0)), name='inv_cust_mth_receipt_gte_0'), models.CheckConstraint(condition=models.Q(('issue_qty_lac__gte', 0)), name='inv_cust_mth_issue_gte_0')],
            },
        ),
    ]
