# Generated by Django 6.0.3 on 2026-05-13 16:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('masters', '0005_operator_master_and_dpr_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrnStkAdjDtl1',
            fields=[
                ('dtl1_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Total of batch quantities (stored for reporting).', max_digits=12, verbose_name='Quantity')),
                ('line_remarks', models.CharField(blank=True, default='', max_length=20, verbose_name='Remarks')),
                ('item', models.ForeignKey(blank=True, db_column='item_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_adj_lines', to='masters.mstitem', verbose_name='Item')),
                ('product', models.ForeignKey(blank=True, db_column='prod_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_adj_lines', to='masters.mstprod', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Stock adjustment line',
                'verbose_name_plural': 'Stock adjustment lines',
                'db_table': 'TrnStkAdjDtl1',
                'ordering': ['dtl1_id'],
            },
        ),
        migrations.CreateModel(
            name='TrnStkAdjDtl2',
            fields=[
                ('dtl2_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_no', models.CharField(max_length=100, verbose_name='Batch no.')),
                ('mfg_date', models.DateField(blank=True, null=True, verbose_name='Mfg date')),
                ('exp_date', models.DateField(blank=True, null=True, verbose_name='Exp date')),
                ('batch_qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Batch qty')),
                ('line', models.ForeignKey(db_column='stk_adj_dtl1_id', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.trnstkadjdtl1', verbose_name='Line')),
            ],
            options={
                'verbose_name': 'Stock adjustment batch',
                'verbose_name_plural': 'Stock adjustment batches',
                'db_table': 'TrnStkAdjDtl2',
                'ordering': ['dtl2_id'],
            },
        ),
        migrations.CreateModel(
            name='TrnStkAdjHed',
            fields=[
                ('stk_adj_id', models.AutoField(primary_key=True, serialize=False)),
                ('stk_adj_dt', models.DateField(verbose_name='Document date')),
                ('stk_adj_type', models.CharField(choices=[('O', 'Opening balance'), ('A', 'Stock adjustment')], max_length=1, verbose_name='Adjustment type')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('customer', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='masters.mstcust', verbose_name='Customer')),
                ('item_type', models.ForeignKey(db_column='item_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='masters.mstitemtype', verbose_name='Item type')),
            ],
            options={
                'verbose_name': 'Stock adjustment (header)',
                'verbose_name_plural': 'Stock adjustments (headers)',
                'db_table': 'TrnStkAdjHed',
                'ordering': ['-stk_adj_dt', '-stk_adj_id'],
            },
        ),
        migrations.AddField(
            model_name='trnstkadjdtl1',
            name='header',
            field=models.ForeignKey(db_column='stk_adj_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.trnstkadjhed', verbose_name='Adjustment'),
        ),
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('inv_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_no', models.CharField(default='', max_length=100, verbose_name='Batch no.')),
                ('mfg_date', models.DateField(blank=True, null=True, verbose_name='Mfg date')),
                ('exp_date', models.DateField(blank=True, null=True, verbose_name='Exp date')),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Available qty')),
                ('reserved_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Reserved for future allocation (not decremented from available yet).', max_digits=12, verbose_name='Reserved qty')),
                ('last_trn_date', models.DateField(blank=True, null=True, verbose_name='Last transaction date')),
                ('last_trn_type', models.CharField(blank=True, max_length=30, verbose_name='Last transaction type')),
                ('ref_doc_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Reference document id')),
                ('ref_doc_type', models.CharField(blank=True, max_length=30, verbose_name='Reference document type')),
                ('customer', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stock_rows', to='masters.mstcust', verbose_name='Customer')),
                ('item', models.ForeignKey(blank=True, db_column='item_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stock_rows', to='masters.mstitem', verbose_name='Item')),
                ('item_category', models.ForeignKey(db_column='item_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stock_rows', to='masters.mstprodcat', verbose_name='Item category')),
                ('product', models.ForeignKey(blank=True, db_column='prod_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stock_rows', to='masters.mstprod', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Inventory stock',
                'verbose_name_plural': 'Inventory stock',
                'db_table': 'InventoryStock',
                'ordering': ['customer', 'batch_no', 'product', 'item'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('item__isnull', True), ('product__isnull', False)), models.Q(('item__isnull', False), ('product__isnull', True)), _connector='OR'), name='inv_stock_product_xor_item'), models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('customer', 'product', 'item_category', 'batch_no', 'mfg_date', 'exp_date'), name='inv_stock_uniq_cust_prod_batch'), models.UniqueConstraint(condition=models.Q(('item__isnull', False)), fields=('customer', 'item', 'item_category', 'batch_no', 'mfg_date', 'exp_date'), name='inv_stock_uniq_cust_item_batch')],
            },
        ),
        migrations.AddConstraint(
            model_name='trnstkadjdtl1',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item__isnull', True), ('product__isnull', False)), models.Q(('item__isnull', False), ('product__isnull', True)), _connector='OR'), name='stk_adj_dtl1_prod_xor_item'),
        ),
        migrations.AddConstraint(
            model_name='trnstkadjdtl1',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('header', 'product'), name='uniq_stk_adj_hed_product'),
        ),
        migrations.AddConstraint(
            model_name='trnstkadjdtl1',
            constraint=models.UniqueConstraint(condition=models.Q(('item__isnull', False)), fields=('header', 'item'), name='uniq_stk_adj_hed_item'),
        ),
    ]
