# Generated by Django 6.0.3 on 2026-05-14 08:40

from django.db import migrations, models


def close_zero_qty_rows(apps, schema_editor):
    InventoryStock = apps.get_model('inventory', 'InventoryStock')
    InventoryStock.objects.filter(qty__lte=0).update(is_closed=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inv_stock_unique_cust_sku_batch'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventorystock',
            name='inv_stock_uniq_cust_prod_batch_no',
        ),
        migrations.RemoveConstraint(
            model_name='inventorystock',
            name='inv_stock_uniq_cust_item_batch_no',
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False, help_text='When true, this batch line is finished (qty zero). New receipts use a new row with the same batch no.', verbose_name='Closed'),
        ),
        migrations.RunPython(close_zero_qty_rows, noop),
    ]
