# Generated by Django 6.0.3 on 2026-05-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorystock_opened_in_fy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorystock',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False, help_text='True when available qty is zero (operational batch close). Year-end FY close also finalises exhausted lines tied to that FY via Opened in FY.', verbose_name='Closed'),
        ),
    ]
