# Generated by Django 6.0.3 on 2026-09-24 19:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_consolidate_rm_pm_item_stock'),
        ('masters', '0012_alter_mstexpenses_exp_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHed',
            fields=[
                ('stock_lnkno', models.AutoField(db_column='stock_lnkno', primary_key=True, serialize=False, verbose_name='Stock link no.')),
                ('op_date', models.DateField(db_column='op_date', help_text='Date when this stock row was opened or cut over.', verbose_name='Opening/cutover date')),
                ('batch_no', models.CharField(blank=True, db_column='batch_no', default='', help_text='Blank for RM/PM; required for FG.', max_length=100, verbose_name='Batch no.')),
                ('mfg_date', models.DateField(blank=True, db_column='mfg_date', help_text='FG only.', null=True, verbose_name='Mfg date')),
                ('exp_date', models.DateField(blank=True, db_column='exp_date', help_text='FG only.', null=True, verbose_name='Exp date')),
                ('opn_qty', models.DecimalField(db_column='opn_qty', decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Opening quantity')),
                ('rcpt_qty', models.DecimalField(db_column='rcpt_qty', decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Total receipts')),
                ('issue_qty', models.DecimalField(db_column='issue_qty', decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Total issues')),
                ('closing_qty', models.DecimalField(db_column='closing_qty', decimal_places=3, default=Decimal('0'), help_text='Stored running balance = opn_qty + rcpt_qty - issue_qty.', max_digits=12, verbose_name='Closing balance')),
                ('reserved_qty', models.DecimalField(db_column='reserved_qty', decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Reserved quantity')),
                ('is_closed', models.BooleanField(db_column='is_closed', db_index=True, default=False, help_text='True when closing balance is zero and no reserved quantity exists.', verbose_name='Is closed')),
                ('last_trn_date', models.DateField(blank=True, db_column='last_trn_date', null=True, verbose_name='Last transaction date')),
                ('last_trn_type', models.CharField(blank=True, db_column='last_trn_type', default='', max_length=30, verbose_name='Last transaction type')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='Updated at')),
                ('customer', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.PROTECT, related_name='stock_hed_rows', to='masters.mstcust', verbose_name='Customer')),
                ('financial_year', models.ForeignKey(db_column='financial_year_id', on_delete=django.db.models.deletion.PROTECT, related_name='stock_hed_rows', to='masters.financialyear', verbose_name='Financial year')),
                ('item', models.ForeignKey(blank=True, db_column='item_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_hed_rows', to='masters.mstitem', verbose_name='Item (RM/PM)')),
                ('item_category', models.ForeignKey(blank=True, db_column='item_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_hed_rows', to='masters.mstprodcat', verbose_name='Item category')),
                ('product', models.ForeignKey(blank=True, db_column='prod_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_hed_rows', to='masters.mstprod', verbose_name='Product (FG)')),
            ],
            options={
                'verbose_name': 'Stock balance header',
                'verbose_name_plural': 'Stock balance headers',
                'db_table': 'StockHed',
                'ordering': ['customer', 'product', 'item', 'batch_no'],
            },
        ),
        migrations.CreateModel(
            name='StockDtl',
            fields=[
                ('stock_dtl_id', models.AutoField(db_column='stock_dtl_id', primary_key=True, serialize=False, verbose_name='Stock detail ID')),
                ('tran_id', models.CharField(choices=[('OPN', 'Opening balance'), ('INW', 'Inward RM/PM'), ('DIS', 'RM Dispensing'), ('DPR', 'DPR Finished Goods'), ('SLS', 'Sales Invoice Dispatch'), ('STK', 'Stock Adjustment')], db_column='tran_id', max_length=10, verbose_name='Source module code')),
                ('trn_type', models.CharField(choices=[('O', 'Opening'), ('R', 'Receipt'), ('I', 'Issue')], db_column='trn_type', help_text='O = Opening, R = Receipt, I = Issue.', max_length=1, verbose_name='Movement type')),
                ('trn_no', models.CharField(db_column='trn_no', max_length=50, verbose_name='Originating document number/id')),
                ('trn_date', models.DateField(db_column='trn_date', verbose_name='Transaction date')),
                ('quantity', models.DecimalField(db_column='quantity', decimal_places=3, max_digits=12, verbose_name='Movement quantity')),
                ('source_line_id', models.CharField(db_column='source_line_id', db_index=True, help_text='Idempotency key ensuring a document line cannot post twice.', max_length=100, verbose_name='Source line / idempotency key')),
                ('is_reversal', models.BooleanField(db_column='is_reversal', default=False, help_text='True if this movement reverses a previous movement.', verbose_name='Is reversal')),
                ('remarks', models.CharField(blank=True, db_column='remarks', default='', max_length=255, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Created at')),
                ('reversal_of', models.ForeignKey(blank=True, db_column='reversal_of_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='inventory.stockdtl', verbose_name='Reversal of movement')),
                ('stock', models.ForeignKey(db_column='stock_lnkno', on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockhed', verbose_name='Stock header')),
            ],
            options={
                'verbose_name': 'Stock movement detail',
                'verbose_name_plural': 'Stock movement details',
                'db_table': 'StockDtl',
                'ordering': ['trn_date', 'stock_dtl_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='stockhed',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item__isnull', True), ('product__isnull', False)), models.Q(('item__isnull', False), ('product__isnull', True)), _connector='OR'), name='stock_hed_product_xor_item'),
        ),
        migrations.AddConstraint(
            model_name='stockhed',
            constraint=models.CheckConstraint(condition=models.Q(('closing_qty__gte', 0)), name='stock_hed_closing_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='stockhed',
            constraint=models.UniqueConstraint(fields=('financial_year', 'customer', 'item'), name='unique_stock_hed_fy_cust_item'),
        ),
        migrations.AddConstraint(
            model_name='stockhed',
            constraint=models.UniqueConstraint(fields=('financial_year', 'customer', 'product', 'batch_no'), name='unique_stock_hed_fy_cust_prod_batch'),
        ),
        migrations.AddConstraint(
            model_name='stockdtl',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_dtl_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='stockdtl',
            constraint=models.UniqueConstraint(fields=('source_line_id',), name='unique_stock_dtl_source_line_id'),
        ),
    ]
