# Generated by Django 6.0.3 on 2026-04-20 07:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrnInwHed',
            fields=[
                ('inward_id', models.AutoField(primary_key=True, serialize=False)),
                ('inward_dt', models.DateField(verbose_name='Inward Date')),
                ('working_year', models.CharField(db_index=True, editable=False, max_length=9, verbose_name='Financial Year')),
                ('register_no', models.CharField(help_text='Format: R- plus digits (e.g. R-00001 … R-99999, then R-100000).', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^R-\\d+$', 'Must match R- plus digits (e.g. R-00001 or R-100000).')], verbose_name='Register No.')),
                ('grn_no', models.CharField(help_text='Format RM-… or PM-… (shared sequence; e.g. RM-00001 … RM-100000).', max_length=50, verbose_name='GRN No.')),
                ('inv_no', models.CharField(max_length=100, verbose_name='Invoice No.')),
                ('inv_dt', models.DateField(verbose_name='Invoice Date')),
                ('vehicle_no', models.CharField(max_length=50, verbose_name='Vehicle No.')),
                ('driver_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Driver Name')),
                ('driver_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='Driver Contact')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('documents', models.CharField(blank=True, help_text='Relative path under MEDIA_ROOT for the uploaded header document (PDF/image).', max_length=500, null=True, verbose_name='Documents')),
                ('customer', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.PROTECT, related_name='inwards', to='masters.mstcust', verbose_name='Customer')),
                ('financial_year', models.ForeignKey(db_column='fy_id', editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='inwards', to='masters.financialyear', verbose_name='Financial Year')),
                ('grn_category', models.ForeignKey(db_column='grn_prod_cat_id', on_delete=django.db.models.deletion.PROTECT, related_name='inwards', to='masters.mstprodcat', verbose_name='GRN Type (RM / PM)')),
                ('supplier', models.ForeignKey(db_column='supl_id', on_delete=django.db.models.deletion.PROTECT, related_name='inwards', to='masters.mstsupplier', verbose_name='Supplier')),
                ('transporter', models.ForeignKey(db_column='transport_id', on_delete=django.db.models.deletion.PROTECT, related_name='inwards', to='masters.msttransport', verbose_name='Transporter')),
            ],
            options={
                'verbose_name': 'Inward (Header)',
                'verbose_name_plural': 'Inwards (Headers)',
                'db_table': 'TrnInwHed',
                'ordering': ['-inward_dt', '-inward_id'],
            },
        ),
        migrations.CreateModel(
            name='TrnInwDtl2',
            fields=[
                ('dtl2_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_no', models.CharField(max_length=100, verbose_name='Batch No.')),
                ('pack_style', models.CharField(db_column='pkg_style_id', help_text='Free-text packing style for this batch line.', max_length=30, verbose_name='Packing Style')),
                ('mfg_dt', models.DateField(blank=True, null=True, verbose_name='Manufacturing Date')),
                ('exp_dt', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('batch_qty', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Batch Qty')),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.PROTECT, related_name='inward_batches', to='masters.mstitem')),
                ('product', models.ForeignKey(blank=True, db_column='prod_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inward_batches', to='masters.mstprod', verbose_name='Product')),
                ('inward', models.ForeignKey(db_column='inward_id', on_delete=django.db.models.deletion.CASCADE, related_name='batch_lines', to='transactions.trninwhed')),
            ],
            options={
                'verbose_name': 'Inward Batch Line',
                'verbose_name_plural': 'Inward Batch Lines',
                'db_table': 'TrnInwDtl2',
            },
        ),
        migrations.CreateModel(
            name='TrnInwDtl1',
            fields=[
                ('dtl1_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantity')),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.PROTECT, related_name='inward_lines', to='masters.mstitem')),
                ('uom', models.ForeignKey(db_column='uom_id', on_delete=django.db.models.deletion.PROTECT, related_name='inward_lines', to='masters.mstuom', verbose_name='UOM')),
                ('inward', models.ForeignKey(db_column='inward_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.trninwhed')),
            ],
            options={
                'verbose_name': 'Inward Item Line',
                'verbose_name_plural': 'Inward Item Lines',
                'db_table': 'TrnInwDtl1',
            },
        ),
        migrations.CreateModel(
            name='TrnSlsOrdHed',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('ord_rec_dt', models.DateField(verbose_name='Order record date')),
                ('cust_ord_id', models.CharField(max_length=20, verbose_name='Customer order ID')),
                ('cust_ord_date', models.DateField(verbose_name='Customer order date')),
                ('delivery_add', models.CharField(blank=True, max_length=200, null=True, verbose_name='Delivery address')),
                ('taxable_val', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Taxable value')),
                ('pkg_fwd_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Packing / forwarding amount')),
                ('frieght_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Freight amount')),
                ('oth_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Other charges')),
                ('cgst_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='CGST amount')),
                ('sgst_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='SGST amount')),
                ('igst_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IGST amount')),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Round off')),
                ('total_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total amount')),
                ('terms_cond', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Terms and conditions')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='Remarks')),
                ('working_year', models.CharField(db_index=True, editable=False, max_length=9, verbose_name='Working year')),
                ('document_path', models.CharField(blank=True, max_length=150, null=True, verbose_name='Document path')),
                ('customer', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='masters.mstcust', verbose_name='Customer')),
                ('financial_year', models.ForeignKey(db_column='fy_id', editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='masters.financialyear', verbose_name='Financial year')),
            ],
            options={
                'verbose_name': 'Sales order (header)',
                'verbose_name_plural': 'Sales orders (headers)',
                'db_table': 'TrnSlsOrdHed',
                'ordering': ['-ord_rec_dt', '-order_id'],
            },
        ),
        migrations.CreateModel(
            name='TrnSlsOrdDtl2',
            fields=[
                ('dtl2_id', models.AutoField(primary_key=True, serialize=False)),
                ('disp_sche_dt', models.DateField(verbose_name='Dispatch schedule date')),
                ('disp_qty', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dispatch qty')),
                ('remarks', models.CharField(blank=True, max_length=20, null=True, verbose_name='Remarks')),
                ('product', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_dispatches', to='masters.mstprod')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_lines', to='transactions.trnslsordhed')),
            ],
            options={
                'verbose_name': 'Sales order dispatch',
                'verbose_name_plural': 'Sales order dispatches',
                'db_table': 'TrnSlsOrdDtl2',
                'ordering': ['disp_sche_dt', 'dtl2_id'],
            },
        ),
        migrations.CreateModel(
            name='TrnSlsOrdDtl1',
            fields=[
                ('dtl1_id', models.AutoField(primary_key=True, serialize=False)),
                ('hsn_no', models.CharField(max_length=50, verbose_name='HSN no.')),
                ('order_qty', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Order qty')),
                ('ord_qty_nos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Order qty (nos.)')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Rate')),
                ('taxable_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Taxable amount')),
                ('gst_type', models.CharField(choices=[('CGST_SGST', 'CGST + SGST'), ('IGST', 'IGST'), ('EXEMPTED', 'Exempted')], max_length=20, verbose_name='GST type')),
                ('gst_per', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='GST %')),
                ('cgst_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='CGST amount')),
                ('sgst_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='SGST amount')),
                ('igst_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IGST amount')),
                ('prod_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Product amount')),
                ('export_type', models.CharField(max_length=100, verbose_name='Export type')),
                ('packing_style', models.ForeignKey(db_column='pkg_style_id', on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='masters.mstpkgstyle', verbose_name='Packing style')),
                ('product', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='masters.mstprod')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.trnslsordhed')),
            ],
            options={
                'verbose_name': 'Sales order line',
                'verbose_name_plural': 'Sales order lines',
                'db_table': 'TrnSlsOrdDtl1',
                'ordering': ['dtl1_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='trninwhed',
            constraint=models.UniqueConstraint(fields=('grn_no', 'financial_year'), name='unique_grn_per_fy'),
        ),
        migrations.AddConstraint(
            model_name='trninwhed',
            constraint=models.CheckConstraint(condition=models.Q(('inv_dt__lte', models.F('inward_dt'))), name='trn_inw_hed_inv_dt_lte_inward_dt'),
        ),
        migrations.AddConstraint(
            model_name='trninwhed',
            constraint=models.CheckConstraint(condition=models.Q(('grn_category_id__in', ['RM', 'PM'])), name='trn_inw_hed_grn_cat_rm_or_pm'),
        ),
        migrations.AddConstraint(
            model_name='trninwdtl2',
            constraint=models.UniqueConstraint(fields=('inward', 'item', 'batch_no'), name='unique_trn_inw_item_batch'),
        ),
        migrations.AddConstraint(
            model_name='trninwdtl2',
            constraint=models.CheckConstraint(condition=models.Q(('mfg_dt__isnull', True), ('exp_dt__isnull', True), ('exp_dt__gt', models.F('mfg_dt')), _connector='OR'), name='trn_inw_dtl2_exp_after_mfg_when_both'),
        ),
        migrations.AddConstraint(
            model_name='trninwdtl2',
            constraint=models.CheckConstraint(condition=models.Q(('batch_qty__gt', 0)), name='trn_inw_dtl2_batch_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='trninwdtl1',
            constraint=models.UniqueConstraint(fields=('inward', 'item'), name='unique_trn_inw_item_dtl1'),
        ),
        migrations.AddConstraint(
            model_name='trninwdtl1',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='trn_inw_dtl1_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='trnslsordhed',
            constraint=models.UniqueConstraint(fields=('customer', 'cust_ord_id'), name='unique_cust_custord_sales'),
        ),
        migrations.AddConstraint(
            model_name='trnslsordhed',
            constraint=models.CheckConstraint(condition=models.Q(('taxable_val__gte', 0)), name='trn_sls_hed_taxable_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trnslsordhed',
            constraint=models.CheckConstraint(condition=models.Q(('pkg_fwd_amt__gte', 0)), name='trn_sls_hed_pkg_fwd_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trnslsordhed',
            constraint=models.CheckConstraint(condition=models.Q(('frieght_amt__gte', 0)), name='trn_sls_hed_freight_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trnslsordhed',
            constraint=models.CheckConstraint(condition=models.Q(('oth_charges__gte', 0)), name='trn_sls_hed_oth_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trnslsordhed',
            constraint=models.CheckConstraint(condition=models.Q(('cgst_amt__gte', 0)), name='trn_sls_hed_cgst_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trnslsordhed',
            constraint=models.CheckConstraint(condition=models.Q(('sgst_amt__gte', 0)), name='trn_sls_hed_sgst_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trnslsordhed',
            constraint=models.CheckConstraint(condition=models.Q(('igst_amt__gte', 0)), name='trn_sls_hed_igst_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trnslsordhed',
            constraint=models.CheckConstraint(condition=models.Q(('total_amt__gte', 0)), name='trn_sls_hed_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trnslsordhed',
            constraint=models.CheckConstraint(condition=models.Q(('round_off__gte', -1), ('round_off__lte', 1)), name='trn_sls_hed_round_off_range'),
        ),
        migrations.AddConstraint(
            model_name='trnslsordhed',
            constraint=models.CheckConstraint(condition=models.Q(('cust_ord_date__lte', models.F('ord_rec_dt'))), name='trn_sls_hed_custord_dt_lte_ordrec'),
        ),
        migrations.AddConstraint(
            model_name='trnslsorddtl2',
            constraint=models.UniqueConstraint(fields=('order', 'product', 'disp_sche_dt'), name='unique_trn_sls_ord_dispatch_dt'),
        ),
        migrations.AddConstraint(
            model_name='trnslsorddtl2',
            constraint=models.CheckConstraint(condition=models.Q(('disp_qty__gt', 0)), name='trn_sls_dtl2_dispqty_positive'),
        ),
        migrations.AddConstraint(
            model_name='trnslsorddtl1',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique_trn_sls_ord_line_prod'),
        ),
        migrations.AddConstraint(
            model_name='trnslsorddtl1',
            constraint=models.CheckConstraint(condition=models.Q(('order_qty__gt', 0)), name='trn_sls_dtl1_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='trnslsorddtl1',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='trn_sls_dtl1_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='trnslsorddtl1',
            constraint=models.CheckConstraint(condition=models.Q(('taxable_amt__gte', 0)), name='trn_sls_dtl1_taxable_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trnslsorddtl1',
            constraint=models.CheckConstraint(condition=models.Q(('ord_qty_nos__gte', 0)), name='trn_sls_dtl1_ordnos_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trnslsorddtl1',
            constraint=models.CheckConstraint(condition=models.Q(('gst_per__gte', 0)), name='trn_sls_dtl1_gstper_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trnslsorddtl1',
            constraint=models.CheckConstraint(condition=models.Q(('gst_per__lte', 100)), name='trn_sls_dtl1_gstper_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='trnslsorddtl1',
            constraint=models.CheckConstraint(condition=models.Q(('gst_type__in', ['CGST_SGST', 'IGST', 'EXEMPTED'])), name='trn_sls_dtl1_gst_type_enum'),
        ),
    ]
