# Generated by Django 6.0.3 on 2026-04-24 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_mstsupplier_short_name_nullable'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrnBatchHed',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_size_l', models.DecimalField(decimal_places=5, max_digits=12, verbose_name='Batch size (Lacs)')),
                ('batch_size_n', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Batch size (Nos.)')),
                ('partial_yn', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='Partial allocation')),
                ('partial_qty_l', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True, verbose_name='Partial qty (Lacs)')),
                ('partial_qty_n', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Partial qty (Nos.)')),
                ('batch_abbr', models.CharField(max_length=3, verbose_name='Batch abbreviation')),
                ('batch_from', models.IntegerField(verbose_name='Batch range from')),
                ('batch_to', models.IntegerField(verbose_name='Batch range to')),
                ('customer', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.PROTECT, related_name='batch_headers', to='masters.mstcust', verbose_name='Customer')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='batch_headers', to='transactions.trnslsordhed', verbose_name='Sales order')),
                ('product', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.PROTECT, related_name='batch_headers', to='masters.mstprod', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Batch allocation (header)',
                'verbose_name_plural': 'Batch allocation (headers)',
                'db_table': 'TrnBatchHed',
                'ordering': ['-batch_id'],
            },
        ),
        migrations.CreateModel(
            name='TrnBatchDtl',
            fields=[
                ('dtl_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_no', models.CharField(max_length=15, unique=True, verbose_name='Batch no.')),
                ('batch_qty_l', models.DecimalField(decimal_places=5, max_digits=12, verbose_name='Batch qty (Lacs)')),
                ('batch_qty_n', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Batch qty (Nos.)')),
                ('mfg_dt', models.CharField(help_text='Manufacturing month, e.g. JAN-2026', max_length=8, verbose_name='Mfg. (MMM-YYYY)')),
                ('exp_dt', models.CharField(help_text='Expiry month, e.g. DEC-2028', max_length=8, verbose_name='Exp. (MMM-YYYY)')),
                ('log_sheet_flg', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='Log sheet')),
                ('batch', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.trnbatchhed', verbose_name='Batch header')),
            ],
            options={
                'verbose_name': 'Batch allocation line',
                'verbose_name_plural': 'Batch allocation lines',
                'db_table': 'TrnBatchDtl',
                'ordering': ['dtl_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='trnbatchhed',
            constraint=models.CheckConstraint(condition=models.Q(('batch_from__lte', models.F('batch_to'))), name='trn_batch_hed_from_lte_to'),
        ),
        migrations.AddConstraint(
            model_name='trnbatchhed',
            constraint=models.CheckConstraint(condition=models.Q(('partial_yn__in', ['Y', 'N'])), name='trn_batch_hed_partial_yn_enum'),
        ),
        migrations.AddConstraint(
            model_name='trnbatchdtl',
            constraint=models.CheckConstraint(condition=models.Q(('log_sheet_flg__in', ['Y', 'N'])), name='trn_batch_dtl_logsheet_enum'),
        ),
        migrations.AddConstraint(
            model_name='trnbatchdtl',
            constraint=models.CheckConstraint(condition=models.Q(('batch_qty_l__gt', 0)), name='trn_batch_dtl_qty_l_positive'),
        ),
        migrations.AddConstraint(
            model_name='trnbatchdtl',
            constraint=models.CheckConstraint(condition=models.Q(('batch_qty_n__gte', 0)), name='trn_batch_dtl_qty_n_gte_0'),
        ),
    ]
