# Generated by Django — optional ARN no. on inward batch lines.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_trnslsorddtl1_remaining_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='trninwdtl2',
            name='arn_no',
            field=models.CharField(
                blank=True,
                default='',
                max_length=15,
                verbose_name='ARN no.',
            ),
        ),
    ]
