# Generated by Django 5.x on 2026-05-07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_mstbom_batch_size_batch_nos'),
        ('transactions', '0008_trninwdtl2_arn_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrnlssHed',
            fields=[
                ('dispensing_id', models.AutoField(db_column='Dispensing_Id', primary_key=True, serialize=False)),
                ('dispensing_dt', models.DateField(db_column='Dispensing_dt', verbose_name='Dispensing date')),
                ('lot_no', models.PositiveIntegerField(db_column='Lot_no', verbose_name='No. of lots')),
                ('dispensed_by', models.CharField(db_column='Dispensed_by', max_length=150, verbose_name='Dispensed by')),
                ('worker_name', models.CharField(db_column='Worker_name', max_length=150, verbose_name='Worker name')),
                ('checked_by', models.CharField(blank=True, db_column='Checked_by', max_length=150, null=True, verbose_name='Checked by')),
                ('verified_by', models.CharField(blank=True, db_column='Verified_by', max_length=150, null=True, verbose_name='Verified by')),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=100, null=True, verbose_name='Remarks')),
                ('batch_line', models.ForeignKey(db_column='Batch_id', on_delete=django.db.models.deletion.PROTECT, related_name='rm_dispensings', to='transactions.trnbatchdtl', verbose_name='Batch')),
                ('customer', models.ForeignKey(db_column='Cust_id', on_delete=django.db.models.deletion.PROTECT, related_name='rm_dispensings', to='masters.mstcust', verbose_name='Customer')),
                ('machine', models.ForeignKey(db_column='Machine_id', on_delete=django.db.models.deletion.PROTECT, related_name='rm_dispensings', to='masters.mstmachine', verbose_name='Machine')),
                ('product', models.ForeignKey(db_column='Prod_id', on_delete=django.db.models.deletion.PROTECT, related_name='rm_dispensings', to='masters.mstprod', verbose_name='Product')),
                ('specification', models.ForeignKey(db_column='Spec_id', on_delete=django.db.models.deletion.PROTECT, related_name='rm_dispensings', to='masters.mstbomrmhed', verbose_name='Specification')),
            ],
            options={
                'db_table': 'TrnlssHed',
                'ordering': ['-dispensing_dt', '-dispensing_id'],
                'verbose_name': 'RM dispensing (header)',
                'verbose_name_plural': 'RM dispensings (headers)',
            },
        ),
        migrations.CreateModel(
            name='TrnlssDtl',
            fields=[
                ('dtl_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty_per_lakh', models.DecimalField(db_column='Qty_PerLack', decimal_places=3, max_digits=12, verbose_name='Qty per lakh')),
                ('issue_qty', models.DecimalField(db_column='Issue_qty', decimal_places=3, max_digits=12, verbose_name='Dispensing qty')),
                ('issue_add_qty', models.DecimalField(db_column='Issue_AddQty', decimal_places=3, default=0, max_digits=12, verbose_name='Additional qty')),
                ('issue_date', models.DateField(db_column='Issue_date', verbose_name='Dispensing date')),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=20, null=True, verbose_name='Remarks')),
                ('dispensing', models.ForeignKey(db_column='Dispensing_Id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.trnlsshed', verbose_name='Dispensing')),
                ('item', models.ForeignKey(db_column='Item_id', on_delete=django.db.models.deletion.PROTECT, related_name='rm_dispensing_lines', to='masters.mstitem', verbose_name='Item')),
                ('stage', models.ForeignKey(db_column='Stage_id', on_delete=django.db.models.deletion.PROTECT, related_name='rm_dispensing_lines', to='masters.mstpdnstage', verbose_name='Production stage')),
            ],
            options={
                'db_table': 'TrnlssDtl',
                'ordering': ['dtl_id'],
                'verbose_name': 'RM dispensing (line)',
                'verbose_name_plural': 'RM dispensing (lines)',
            },
        ),
        migrations.AddConstraint(
            model_name='trnlsshed',
            constraint=models.CheckConstraint(condition=models.Q(('lot_no__gt', 0)), name='trnlss_hed_lot_no_positive'),
        ),
        migrations.AddConstraint(
            model_name='trnlssdtl',
            constraint=models.UniqueConstraint(fields=('dispensing', 'stage', 'item'), name='unique_trnlss_stage_item_per_dispensing'),
        ),
        migrations.AddConstraint(
            model_name='trnlssdtl',
            constraint=models.CheckConstraint(condition=models.Q(('qty_per_lakh__gte', 0)), name='trnlss_dtl_qty_per_lakh_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trnlssdtl',
            constraint=models.CheckConstraint(condition=models.Q(('issue_qty__gte', 0)), name='trnlss_dtl_issue_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trnlssdtl',
            constraint=models.CheckConstraint(condition=models.Q(('issue_add_qty__gte', 0)), name='trnlss_dtl_issue_add_qty_gte_0'),
        ),
    ]

