# Generated by Django 5.x on 2026-05-07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_trnlss_rm_dispensing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trnlsshed',
            name='batch_line',
            field=models.ForeignKey(
                db_column='Batch_id',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='rm_dispensings',
                to='transactions.trnlogsheet',
                verbose_name='Log sheet',
            ),
        ),
    ]

