# Generated by Django 5.x on 2026-05-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_trnlsshed_use_logsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='trnlogsheet',
            name='rm_disp_flg',
            field=models.CharField(
                choices=[('Y', 'Yes'), ('N', 'No')],
                default='N',
                help_text='Y when all BOM stages have at least one RM dispensing record for this log sheet/spec.',
                max_length=1,
                verbose_name='RM dispensing completed',
            ),
        ),
        migrations.AddConstraint(
            model_name='trnlogsheet',
            constraint=models.CheckConstraint(
                condition=models.Q(('rm_disp_flg__in', ['Y', 'N'])),
                name='trn_logsheet_rm_disp_enum',
            ),
        ),
    ]

