# Generated by Django 5.x on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_trnlogsheet_rm_disp_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trninwdtl2',
            name='arn_no',
            field=models.CharField(
                blank=True,
                default='',
                max_length=20,
                verbose_name='ARN no.',
            ),
        ),
    ]

