# Generated by Django 6.0.3 on 2026-05-10 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_bom_specname_product_unique'),
        ('transactions', '0012_trninwdtl2_arn_no_20'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrnDpr',
            fields=[
                ('trn_dpr_id', models.AutoField(db_column='TrnDpr_id', primary_key=True, serialize=False)),
                ('trn_dpr_dt', models.DateField(db_column='TrnDpr_dt', verbose_name='DPR date')),
                ('shift_id', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('General', 'General')], db_column='Shift_id', max_length=10, verbose_name='Shift')),
                ('machine_working', models.CharField(choices=[('working', 'Working'), ('not_working', 'Not working')], db_column='Machine_working', default='working', max_length=20, verbose_name='Machine status')),
                ('batch_rem', models.CharField(blank=True, db_column='Batch_rem', default='', max_length=30, verbose_name='Batch remarks')),
                ('lot_no', models.PositiveSmallIntegerField(db_column='Lot_no', verbose_name='Lot nos.')),
                ('qty_kg', models.DecimalField(db_column='Qty_kg', decimal_places=3, default=0, max_digits=12, verbose_name='Qty (kg)')),
                ('qty_nos', models.PositiveBigIntegerField(db_column='Qty_nos', default=0, verbose_name='Qty (nos.)')),
                ('section_qty', models.DecimalField(blank=True, db_column='Section_qty', decimal_places=3, max_digits=12, null=True, verbose_name='Section qty')),
                ('start_time', models.TimeField(db_column='Start_time', verbose_name='Start time')),
                ('end_time', models.TimeField(db_column='End_time', verbose_name='End time')),
                ('total_time', models.CharField(blank=True, db_column='Total_time', default='', max_length=24, verbose_name='Total time')),
                ('operator1', models.CharField(blank=True, db_column='Operator1', default='', max_length=30, verbose_name='Operator (1)')),
                ('operator2', models.CharField(blank=True, db_column='Operator2', default='', max_length=30, verbose_name='Operator (2)')),
                ('no_of_helper', models.PositiveSmallIntegerField(db_column='No_of_Helper', default=0, verbose_name='No. of helpers')),
                ('remarks', models.CharField(blank=True, db_column='Remarks', default='', max_length=500, verbose_name='Remarks')),
                ('multi_batch_gran_lub', models.BooleanField(db_column='Multi_batch_gran_lub', default=False, verbose_name='Multi-batch (granulation / lubrication)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Updated_at')),
                ('batch_line', models.ForeignKey(blank=True, db_column='TrnBatch_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dpr_entries', to='transactions.trnbatchdtl', verbose_name='Batch allocation line')),
                ('created_by', models.ForeignKey(blank=True, db_column='Created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpr_entries_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('customer', models.ForeignKey(blank=True, db_column='Cust_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dpr_entries', to='masters.mstcust', verbose_name='Customer')),
                ('log_sheet', models.ForeignKey(blank=True, db_column='LogSheet_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dpr_entries', to='transactions.trnlogsheet', verbose_name='Log sheet')),
                ('machine', models.ForeignKey(db_column='Machine_id', on_delete=django.db.models.deletion.PROTECT, related_name='dpr_entries', to='masters.mstmachine', verbose_name='Machine')),
                ('product', models.ForeignKey(blank=True, db_column='Prod_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dpr_entries', to='masters.mstprod', verbose_name='Product')),
                ('section', models.ForeignKey(db_column='Section_id', on_delete=django.db.models.deletion.PROTECT, related_name='dpr_entries', to='masters.mstsection', verbose_name='Section')),
                ('specification', models.ForeignKey(blank=True, db_column='Spec_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dpr_entries', to='masters.mstbomrmhed', verbose_name='Specification')),
            ],
            options={
                'verbose_name': 'Daily production report',
                'verbose_name_plural': 'Daily production reports',
                'db_table': 'TrnDPR',
                'ordering': ['-trn_dpr_dt', '-trn_dpr_id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('shift_id__in', ['Day', 'Night', 'General'])), name='trn_dpr_shift_enum'), models.CheckConstraint(condition=models.Q(('machine_working__in', ['working', 'not_working'])), name='trn_dpr_machine_working_enum'), models.CheckConstraint(condition=models.Q(('no_of_helper__lte', 999)), name='trn_dpr_helpers_max'), models.UniqueConstraint(condition=models.Q(('batch_line__isnull', False)), fields=('batch_line', 'log_sheet', 'machine', 'shift_id', 'section', 'trn_dpr_dt'), name='unique_dpr_batch_logsheet_machine_shift_section_dt')],
            },
        ),
    ]
