# Generated by Django 6.0.3

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_trn_dpr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trndpr',
            name='multi_batch_gran_lub',
        ),
    ]
