# Generated by Django 6.0.3

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_remove_trndpr_multi_batch_gran_lub'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrnDprInputBatch',
            fields=[
                ('input_id', models.AutoField(db_column='TrnDprInputBatch_id', primary_key=True, serialize=False)),
                (
                    'batch_line',
                    models.ForeignKey(
                        db_column='TrnBatch_id',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='dpr_input_links',
                        to='transactions.trnbatchdtl',
                        verbose_name='Batch allocation line',
                    ),
                ),
                (
                    'dpr',
                    models.ForeignKey(
                        db_column='TrnDpr_id',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='input_batches',
                        to='transactions.trndpr',
                        verbose_name='DPR',
                    ),
                ),
            ],
            options={
                'verbose_name': 'DPR input batch',
                'verbose_name_plural': 'DPR input batches',
                'db_table': 'TrnDPRInputBatch',
                'ordering': ['input_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='trndprinputbatch',
            constraint=models.UniqueConstraint(fields=('dpr', 'batch_line'), name='unique_dpr_input_batch_line'),
        ),
        migrations.AddConstraint(
            model_name='trndpr',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(batch_line__isnull=True, log_sheet__isnull=True)
                    | models.Q(batch_line__isnull=False, log_sheet__isnull=False)
                ),
                name='trn_dpr_batch_logsheet_both_or_neither',
            ),
        ),
    ]
