# Generated by Django 6.0.3 on 2026-05-11 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_operator_master_and_dpr_fk'),
        ('transactions', '0016_dpr_input_logsheet_batch_lakh'),
    ]

    operations = [
        migrations.RemoveField(model_name='trndpr', name='operator1'),
        migrations.RemoveField(model_name='trndpr', name='operator2'),
        migrations.AddField(
            model_name='trndpr',
            name='operator1',
            field=models.ForeignKey(
                blank=True,
                db_column='Operator1_id',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='dpr_entries_primary',
                to='masters.mstoperator',
                verbose_name='Operator (1)',
            ),
        ),
        migrations.AddField(
            model_name='trndpr',
            name='operator2',
            field=models.ForeignKey(
                blank=True,
                db_column='Operator2_id',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='dpr_entries_secondary',
                to='masters.mstoperator',
                verbose_name='Operator (2)',
            ),
        ),
    ]
