# Generated by Django 6.0.3 on 2026-05-11 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_operator_master_and_dpr_fk'),
        ('transactions', '0017_operator_master_and_dpr_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrnPkgCont',
            fields=[
                ('pkgcont_id', models.AutoField(db_column='PkgCont_id', primary_key=True, serialize=False)),
                ('pkgcont_date', models.DateField(db_column='PkgCont_Date', verbose_name='Packing date')),
                ('no_of_girls', models.PositiveSmallIntegerField(blank=True, db_column='No_of_Girls', help_text='Packing manpower (optional).', null=True, verbose_name='No. of girls')),
                ('shipper_no', models.PositiveIntegerField(db_column='Shipper_no', help_text='Number of shippers / cartons (1–999999).', verbose_name='Shipper no.')),
                ('qty_nos', models.DecimalField(db_column='Qty_nos', decimal_places=0, max_digits=12, verbose_name='Qty (nos.)')),
                ('qty_loose', models.DecimalField(blank=True, db_column='Qty_loose', decimal_places=0, max_digits=12, null=True, verbose_name='Qty (loose)')),
                ('remarks', models.TextField(blank=True, db_column='Remarks', null=True, verbose_name='Remarks')),
                ('contractor', models.ForeignKey(db_column='Contractor_id', on_delete=django.db.models.deletion.PROTECT, related_name='packing_contractor_entries', to='masters.mstoperator', verbose_name='Contractor')),
                ('log_sheet', models.ForeignKey(db_column='LogSheet_id', on_delete=django.db.models.deletion.PROTECT, related_name='packing_contractor_entries', to='transactions.trnlogsheet', verbose_name='Log sheet (batch)')),
                ('pkg_style', models.ForeignKey(db_column='PkgStyle_id', on_delete=django.db.models.deletion.PROTECT, related_name='packing_contractor_entries', to='masters.mstpkgstyle', verbose_name='Packing style')),
            ],
            options={
                'verbose_name': 'Daily packing (contractor)',
                'verbose_name_plural': 'Daily packing (contractors)',
                'db_table': 'TrnPkgCont',
                'ordering': ['-pkgcont_date', '-pkgcont_id'],
                'constraints': [models.UniqueConstraint(fields=('pkgcont_date', 'log_sheet', 'contractor', 'pkg_style'), name='unique_pkgcont_date_logsheet_contractor_style'), models.CheckConstraint(condition=models.Q(('shipper_no__gte', 1), ('shipper_no__lte', 999999)), name='trn_pkgcont_shipper_range'), models.CheckConstraint(condition=models.Q(('qty_nos__gte', 1)), name='trn_pkgcont_qty_nos_positive'), models.CheckConstraint(condition=models.Q(('no_of_girls__isnull', True), ('no_of_girls__lte', 9999), _connector='OR'), name='trn_pkgcont_girls_max'), models.CheckConstraint(condition=models.Q(('qty_loose__isnull', True), ('qty_loose__gte', 0), _connector='OR'), name='trn_pkgcont_qty_loose_gte_0')],
            },
        ),
    ]
