# Generated by Django — purchase rate per inward item line.

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_trn_pkg_cont'),
    ]

    operations = [
        migrations.AddField(
            model_name='trninwdtl1',
            name='rate',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0'),
                max_digits=12,
                verbose_name='Rate',
            ),
        ),
        migrations.AddConstraint(
            model_name='trninwdtl1',
            constraint=models.CheckConstraint(
                condition=models.Q(rate__gte=0),
                name='trn_inw_dtl1_rate_non_negative',
            ),
        ),
    ]
