# Generated by Django 6.0.3 on 2026-05-14 14:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_mstitem_sample_qty'),
        ('transactions', '0020_mysql_compatible_uniques'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrnSlsHed',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(help_text='Format: SI- plus digits (per financial year sequence).', max_length=15, validators=[django.core.validators.RegexValidator('^SI-\\d+$', 'Must match SI- plus digits (e.g. SI-00001).')], verbose_name='Invoice no.')),
                ('invoice_dt', models.DateField(verbose_name='Invoice date')),
                ('working_year', models.CharField(db_index=True, editable=False, max_length=9, verbose_name='Working year')),
                ('delivery_add', models.TextField(verbose_name='Delivery address')),
                ('taxable_val', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Taxable value')),
                ('pkg_fwd_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Packing / forwarding amount')),
                ('freight_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Freight amount')),
                ('oth_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Other charges')),
                ('cgst_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='CGST amount')),
                ('sgst_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='SGST amount')),
                ('igst_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IGST amount')),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Round off')),
                ('total_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total amount')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('customer', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='masters.mstcust', verbose_name='Customer')),
                ('financial_year', models.ForeignKey(db_column='fy_id', editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='masters.financialyear', verbose_name='Financial year')),
                ('transporter', models.ForeignKey(db_column='transport_id', on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='masters.msttransport', verbose_name='Transporter')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Sales invoice (header)',
                'verbose_name_plural': 'Sales invoices (headers)',
                'db_table': 'TrnSlsHed',
                'ordering': ['-invoice_dt', '-invoice_id'],
            },
        ),
        migrations.CreateModel(
            name='TrnSlsDtl1',
            fields=[
                ('dtl1_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantity (lac)')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Rate')),
                ('taxable_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Taxable amount')),
                ('gst_type', models.CharField(choices=[('CGST_SGST', 'CGST + SGST'), ('IGST', 'IGST'), ('EXEMPTED', 'Exempted')], max_length=20, verbose_name='GST type')),
                ('gst_per', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='GST %')),
                ('cgst_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='CGST amount')),
                ('sgst_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='SGST amount')),
                ('igst_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IGST amount')),
                ('prod_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Product amount')),
                ('order_line', models.ForeignKey(blank=True, db_column='order_dtl1_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_lines', to='transactions.trnslsorddtl1', verbose_name='Sales order line')),
                ('packing_style', models.ForeignKey(db_column='pkg_style_id', on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_lines', to='masters.mstpkgstyle', verbose_name='Packing style')),
                ('product', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_lines', to='masters.mstprod', verbose_name='Product')),
                ('invoice', models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.trnslshed')),
            ],
            options={
                'verbose_name': 'Sales invoice line',
                'verbose_name_plural': 'Sales invoice lines',
                'db_table': 'TrnSlsDtl1',
                'ordering': ['dtl1_id'],
            },
        ),
        migrations.CreateModel(
            name='TrnSlsDtl2',
            fields=[
                ('dtl2_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_qty', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Batch qty (lac)')),
                ('invoice_line', models.ForeignKey(db_column='invoice_dtl1_id', on_delete=django.db.models.deletion.CASCADE, related_name='batch_lines', to='transactions.trnslsdtl1', verbose_name='Invoice line')),
                ('log_sheet', models.ForeignKey(db_column='logsheet_id', on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_batches', to='transactions.trnlogsheet', verbose_name='Log sheet')),
            ],
            options={
                'verbose_name': 'Sales invoice batch line',
                'verbose_name_plural': 'Sales invoice batch lines',
                'db_table': 'TrnSlsDtl2',
                'ordering': ['dtl2_id'],
                'constraints': [models.UniqueConstraint(fields=('invoice_line', 'log_sheet'), name='uniq_trn_sls_inv_dtl2_line_logsheet'), models.CheckConstraint(condition=models.Q(('batch_qty__gt', 0)), name='trn_sls_inv_dtl2_batch_qty_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='trnslshed',
            constraint=models.UniqueConstraint(fields=('invoice_no', 'financial_year'), name='unique_sales_invoice_no_per_fy'),
        ),
        migrations.AddConstraint(
            model_name='trnslshed',
            constraint=models.CheckConstraint(condition=models.Q(('taxable_val__gte', 0)), name='trn_sls_inv_hed_taxable_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trnslshed',
            constraint=models.CheckConstraint(condition=models.Q(('pkg_fwd_amt__gte', 0)), name='trn_sls_inv_hed_pkg_fwd_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trnslshed',
            constraint=models.CheckConstraint(condition=models.Q(('freight_amt__gte', 0)), name='trn_sls_inv_hed_freight_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trnslshed',
            constraint=models.CheckConstraint(condition=models.Q(('oth_charges__gte', 0)), name='trn_sls_inv_hed_oth_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trnslshed',
            constraint=models.CheckConstraint(condition=models.Q(('cgst_amt__gte', 0)), name='trn_sls_inv_hed_cgst_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trnslshed',
            constraint=models.CheckConstraint(condition=models.Q(('sgst_amt__gte', 0)), name='trn_sls_inv_hed_sgst_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trnslshed',
            constraint=models.CheckConstraint(condition=models.Q(('igst_amt__gte', 0)), name='trn_sls_inv_hed_igst_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trnslshed',
            constraint=models.CheckConstraint(condition=models.Q(('total_amt__gte', 0)), name='trn_sls_inv_hed_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trnslshed',
            constraint=models.CheckConstraint(condition=models.Q(('round_off__gte', -1), ('round_off__lte', 1)), name='trn_sls_inv_hed_round_off_range'),
        ),
        migrations.AddConstraint(
            model_name='trnslsdtl1',
            constraint=models.UniqueConstraint(condition=models.Q(('order_line__isnull', False)), fields=('invoice', 'order_line'), name='uniq_trn_sls_inv_dtl1_inv_ordline'),
        ),
        migrations.AddConstraint(
            model_name='trnslsdtl1',
            constraint=models.UniqueConstraint(condition=models.Q(('order_line__isnull', True)), fields=('invoice', 'product', 'packing_style'), name='uniq_trn_sls_inv_dtl1_inv_prod_pkg'),
        ),
        migrations.AddConstraint(
            model_name='trnslsdtl1',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='trn_sls_inv_dtl1_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='trnslsdtl1',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='trn_sls_inv_dtl1_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='trnslsdtl1',
            constraint=models.CheckConstraint(condition=models.Q(('taxable_amt__gte', 0)), name='trn_sls_inv_dtl1_taxable_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trnslsdtl1',
            constraint=models.CheckConstraint(condition=models.Q(('gst_per__gte', 0)), name='trn_sls_inv_dtl1_gstper_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trnslsdtl1',
            constraint=models.CheckConstraint(condition=models.Q(('gst_per__lte', 100)), name='trn_sls_inv_dtl1_gstper_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='trnslsdtl1',
            constraint=models.CheckConstraint(condition=models.Q(('gst_type__in', ['CGST_SGST', 'IGST', 'EXEMPTED'])), name='trn_sls_inv_dtl1_gst_type_enum'),
        ),
    ]
