# Generated by Django 6.0.3 on 2026-05-14 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_sales_invoice_trn_sls_hed'),
    ]

    operations = [
        migrations.AddField(
            model_name='trnslshed',
            name='reference_order',
            field=models.ForeignKey(blank=True, db_column='ref_order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_as_reference', to='transactions.trnslsordhed', verbose_name='Reference sales order'),
        ),
    ]
