# Generated by Django 6.0.3 on 2026-05-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_sales_order_line_sale_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='trninwdtl1',
            name='pkgstyle',
            field=models.CharField(db_column='pkg_style', default='A-Salary', help_text='Free-text packing style for this item line.', max_length=30, verbose_name='Pkg Style'),
            preserve_default=False,
        ),
    ]
