# Generated by Django 6.0.3 on 2026-05-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_trninwdtl1_pkgstyle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trninwdtl1',
            name='pkgstyle',
        ),
        migrations.AddField(
            model_name='trninwdtl1',
            name='pkg_style',
            field=models.CharField(blank=True, help_text='Free-text packing style for this item line.', max_length=30, verbose_name='Pkg_Style'),
        ),
    ]
