# Generated by Django 6.0.3 on 2026-05-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_remove_trninwdtl1_pkgstyle_trninwdtl1_pkg_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trninwhed',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vehicle No.'),
        ),
    ]
