# Generated by Django 6.0.3 on 2026-09-26 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_alter_mstexpenses_exp_group'),
        ('transactions', '0027_trndpr_operators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trninwhed',
            name='transporter',
            field=models.ForeignKey(blank=True, db_column='transport_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inwards', to='masters.msttransport', verbose_name='Transporter'),
        ),
    ]
