# Generated by Django 6.0.3 on 2026-05-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Report access',
                'verbose_name_plural': 'Report access',
                'permissions': [('view_master_reports', 'Can view and export master reports')],
            },
        ),
    ]
